# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='recent_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='recent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
